MOV BL,00H;
MOV BH,00H;
MOV SI,1100H;
MOV CL,01H;
MOV CH, [SI];
INC SI;
LOOP: MOV AL,[SI];
     SHL AL,CL;
     JC NEGATIVE;
     INC BL;
     JMP NEXT;
NEGATIVE: INC BH;
NEXT: ADD SI,01H;
DEC CH;
JNZ LOOP;
MOV [1200],BL;
MOV [1201],BH;
HLT 